services:
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - "8000:8000" # Kong proxy port
      - "8443:8443" # Kong proxy SSL port
      - "8001:8001" # Kong Admin API port
      - "8444:8444" # Kong Admin API SSL port
      - "8002:8002" # Kong Admin GUI port
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml:ro

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./services/data-ingestion/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sustainable_consumption
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  data-ingestion:
    build: ./services/data-ingestion
    restart: always
    depends_on:
      - mosquitto
      - mysql
      - kong
    environment:
      PORT: 3001
      BROKER: "mosquitto"
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASS: "admin"
      DB_NAME: "sustainable_consumption"

  auth-service:
    build: ./services/auth-service
    restart: always
    environment:
      PORT: 3000
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASS: "admin"
      DB_NAME: "sustainable_consumption"
    ports:
      - "3000:3000"
    depends_on:
      - kong
      - mysql

  prediction-service:
    build: ./services/prediction-service
    restart: always
    environment:
      PORT: 3002
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASS: "admin"
      DB_NAME: "sustainable_consumption"
    ports:
      - "3002:3002"
    depends_on:
      - kong
      - mysql

volumes:
  mysql_data:
  mosquitto_data:
  mosquitto_log:
