services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sensor_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./services/data-ingestion/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./services/data-ingestion/mosquitto.conf:/mosquitto/config/mosquitto.conf
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - "8000:8000" # Kong proxy port
      - "8443:8443" # Kong proxy SSL port
      - "8001:8001" # Kong Admin API port
      - "8444:8444" # Kong Admin API SSL port
      - "8002:8002" # Kong Admin GUI port
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml:ro

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./services/data-ingestion/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sustainable_consumption
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  data-ingestion:
    build: ./services/data-ingestion
    restart: always
    depends_on:
      - mosquitto
      - mysql
      - kong
    environment:
      PORT: 3001
      BROKER: "mosquitto"
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASS: "admin"
      DB_NAME: "sustainable_consumption"

  auth-service:
    build: ./services/auth-service
    restart: always
    environment:
      PORT: 3000
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASS: "admin"
      DB_NAME: "sustainable_consumption"
    ports:
      - "3000:3000"
    depends_on:
      - kong
      - mysql

  prediction-service:
    build: ./services/prediction-service
    restart: always
    environment:
      PORT: 3002
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASS: "admin"
      DB_NAME: "sustainable_consumption"
    ports:
      - "3002:3002"
    depends_on:
      - kong
      - mysql
  data-ingestion:
    build:
      context: ./services/data-ingestion
    depends_on:
      - mosquitto
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=sensor_data
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
  alert-service:
    build:
      context: ./services/alert-service
    depends_on:
      - mosquitto
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=sensor_data
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883

volumes:
  mosquitto_data:
  mysql_data:
  mosquitto_log: