services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sensor_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./services/data-ingestion/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./services/data-ingestion/mosquitto.conf:/mosquitto/config/mosquitto.conf
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - "8000:8000" # Kong proxy port
      - "8443:8443" # Kong proxy SSL port
      - "8001:8001" # Kong Admin API port
      - "8444:8444" # Kong Admin API SSL port
      - "8002:8002" # Kong Admin GUI port
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml:ro

  auth-service:
    build: ./services/auth-service
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - kong

  websocket-bridge:
    build:
      context: ./services
      dockerfile: websocket-bridge.Dockerfile
    ports:
      - "9001:9001"
    depends_on:
      - mosquitto

  data-ingestion:
    build:
      context: ./services/data-ingestion
    depends_on:
      - mosquitto
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=sensor_data
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
volumes:
  mysql-data:


